
import pandas as pd
import numpy as np

class FinancialFeatures:
    """
    Class to engineer financial features for analysis and machine learning.
    """
    
    @staticmethod
    def add_technical_indicators(df):
        """
        Adds SMA, RSI, and Volatility technical indicators.
        """
        df = df.copy()
        
        # Simple Moving Averages
        df['SMA_50'] = df['close'].rolling(window=50).mean()
        df['SMA_200'] = df['close'].rolling(window=200).mean()
        
        # Daily Returns
        df['Daily_Return'] = df['close'].pct_change()
        
        # Volatility (Rolling Std Dev of returns)
        df['Volatility'] = df['Daily_Return'].rolling(window=20).std()
        
        # RSI (Relative Strength Index)
        delta = df['close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))
        
        return df

    @staticmethod
    def add_ml_features(df):
        """
        Adds lag features specifically for the Machine Learning model.
        """
        df = df.copy()
        
        # Lagged Returns (to predict next day based on previous days)
        df['Return_Lag_1'] = df['Daily_Return'].shift(1)
        df['Return_Lag_2'] = df['Daily_Return'].shift(2)
        df['Return_Lag_5'] = df['Daily_Return'].shift(5)
        
        # Volume Change
        df['Volume_Change'] = df['volume'].pct_change()
        df['Volume_Change_Lag_1'] = df['Volume_Change'].shift(1)
        
        # Price Momentum
        df['Momentum_1d'] = df['close'] / df['close'].shift(1) - 1
        
        # Target for Classification: 1 if Price goes UP tomorrow, else 0
        df['Target'] = (df['close'].shift(-1) > df['close']).astype(int)
        
        # Drop NaN values generated by rolling windows and shifting
        df = df.dropna()
        
        return df
